runtime: nodejs20
env: standard
instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

env_variables:
  NODE_ENV: 'production'

handlers:
  - url: /.*
    script: auto
    secure: always